import { Batch, Sample } from "./types";

/**
 * 演示种子数据：仅在 localStorage 为空时写入一次。
 * 覆盖：已封存批次、未封存批次、鉴定不全样本、潜在冲突样本对。
 */
export function seedSamples(): Sample[] {
  return [
    {
      id: "S-001",
      caseId: "CASE-042",
      location: "室外草地",
      temperature: 28.6,
      exposureStage: "肿胀期",
      species: "丝光绿蝇",
      stage: "幼虫",
      sampledAt: "2026-09-10T09:20",
      sampledEnd: "2026-09-10T10:05",
      preservation: "乙醇保存",
      conclusion: "丝光绿蝇三龄幼虫，推断暴露约72小时",
      note: "幼虫活性强，平均体长12mm",
      batchId: "B-01",
      status: "sealed",
      reviewReason: null,
      originBatchId: null,
    },
    {
      id: "S-002",
      caseId: "CASE-042",
      location: "室外草地",
      temperature: 28.4,
      exposureStage: "肿胀期",
      species: "丝光绿蝇",
      stage: "幼虫",
      sampledAt: "2026-09-10T09:40",
      sampledEnd: "2026-09-10T10:30",
      preservation: "乙醇保存",
      conclusion: "丝光绿蝇二至三龄幼虫",
      note: "与 S-001 采样时间窗重叠，随批次提交时会触发冲突检测",
      batchId: null,
      status: "draft",
      reviewReason: null,
      originBatchId: null,
    },
    {
      id: "S-003",
      caseId: "CASE-042",
      location: "阴影区域",
      temperature: 26.1,
      exposureStage: "肿胀期",
      species: "大头金蝇",
      stage: "蛹",
      sampledAt: "2026-09-10T11:00",
      sampledEnd: "2026-09-10T11:40",
      preservation: "冷冻保存",
      conclusion: "大头金蝇蛹期，推断暴露约96小时",
      note: "蛹壳完整，已拍照存档",
      batchId: "B-01",
      status: "sealed",
      reviewReason: null,
      originBatchId: null,
    },
    {
      id: "S-004",
      caseId: "CASE-051",
      location: "水沟边缘",
      temperature: 24.8,
      exposureStage: "腐败期",
      species: "巨尾阿丽蝇",
      stage: "成虫",
      sampledAt: "2026-09-12T08:10",
      sampledEnd: "2026-09-12T08:50",
      preservation: "针插保存",
      conclusion: "巨尾阿丽蝇成虫，已完成拍照",
      note: "",
      batchId: "B-02",
      status: "inBatch",
      reviewReason: null,
      originBatchId: null,
    },
    {
      id: "S-005",
      caseId: "CASE-051",
      location: "水沟边缘",
      temperature: 25.2,
      exposureStage: "腐败期",
      species: "家蝇",
      stage: "成虫",
      sampledAt: "2026-09-12T09:00",
      sampledEnd: "2026-09-12T09:40",
      preservation: "针插保存",
      conclusion: "",
      note: "种属待复核，鉴定结论未填写（演示提交拦截）",
      batchId: "B-02",
      status: "inBatch",
      reviewReason: null,
      originBatchId: null,
    },
    {
      id: "S-006",
      caseId: "CASE-051",
      location: "草丛",
      temperature: 23.9,
      exposureStage: "腐败期",
      species: "丝光绿蝇",
      stage: "卵",
      sampledAt: "2026-09-12T10:00",
      sampledEnd: "2026-09-12T10:20",
      preservation: "乙醇保存",
      conclusion: "丝光绿蝇卵块，推断产后约6小时",
      note: "",
      batchId: null,
      status: "draft",
      reviewReason: null,
      originBatchId: null,
    },
    {
      id: "S-007",
      caseId: "CASE-067",
      location: "室内地板",
      temperature: 21.5,
      exposureStage: "干化期",
      species: "褐尾麻蝇",
      stage: "蛹",
      sampledAt: "2026-09-15T14:00",
      sampledEnd: "2026-09-15T14:35",
      preservation: "冷冻保存",
      conclusion: "褐尾麻蝇蛹期",
      note: "",
      batchId: null,
      status: "draft",
      reviewReason: null,
      originBatchId: null,
    },
    {
      id: "S-008",
      caseId: "CASE-067",
      location: "室内地板",
      temperature: 21.8,
      exposureStage: "干化期",
      species: "家蝇",
      stage: "幼虫",
      sampledAt: "2026-09-15T14:10",
      sampledEnd: "2026-09-15T14:50",
      preservation: "",
      conclusion: "",
      note: "保存方式与鉴定结论待补；与 S-007 时间窗重叠",
      batchId: null,
      status: "draft",
      reviewReason: null,
      originBatchId: null,
    },
    {
      id: "S-009",
      caseId: "CASE-067",
      location: "门口走廊",
      temperature: 22.3,
      exposureStage: "干化期",
      species: "丝光绿蝇",
      stage: "成虫",
      sampledAt: "2026-09-16T09:00",
      sampledEnd: "2026-09-16T09:25",
      preservation: "针插保存",
      conclusion: "丝光绿蝇成虫",
      note: "",
      batchId: null,
      status: "draft",
      reviewReason: null,
      originBatchId: null,
    },
  ];
}

export function seedBatches(): Batch[] {
  return [
    {
      id: "B-01",
      name: "CASE-042 首批鉴定批次",
      createdAt: "2026-09-10 12:00",
      sealed: true,
      sealedAt: "2026-09-11 10:00",
      exportPaused: false,
      records: [
        {
          at: "2026-09-11 10:00",
          action: "sealed",
          detail: "提交封存：2 份样本鉴定齐全，冲突检测通过",
        },
      ],
    },
    {
      id: "B-02",
      name: "CASE-051 水沟样本批次",
      createdAt: "2026-09-12 09:30",
      sealed: false,
      sealedAt: null,
      exportPaused: false,
      records: [],
    },
  ];
}
